version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    expose:
      - '5432'
    ports:
      - '5432:5432'
    env_file:
      - .env
    networks:
      - v1
  scheduler-app:
    container_name: scheduler-app1
    env_file:
      - .env
    expose:
      - 8080
    ports:
      - '8080:8080'
    restart: on-failure:10
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - postgres
    networks:
      - v1 
networks:
  v1:
    driver: bridge